import { Character } from "../../../models/character.model";
import { Homeworld } from "../../../models/homeworld.model";

export const characterMock: Character = {
  name: "Anakin Skywalker",
  height: "188",
  mass: "84",
  hair_color: "blond",
  skin_color: "fair",
  eye_color: "blue",
  birth_year: "41.9BBY",
  gender: "male",
  homeworld: "https://swapi.dev/api/planets/1/",
  films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/5/", "https://swapi.dev/api/films/6/"],
  species: [],
  vehicles: ["https://swapi.dev/api/vehicles/44/", "https://swapi.dev/api/vehicles/46/"],
  starships: [
    "https://swapi.dev/api/starships/39/",
    "https://swapi.dev/api/starships/59/",
    "https://swapi.dev/api/starships/65/",
  ],
  created: "2014-12-10T16:20:44.310000Z",
  edited: "2014-12-20T21:17:50.327000Z",
  url: "https://swapi.dev/api/people/11/",
};

export const paginatedCharactersMock = {
  results: [
    [
      characterMock,
      {
        name: "Wilhuff Tarkin",
        height: "180",
        mass: "unknown",
        hair_color: "auburn, grey",
        skin_color: "fair",
        eye_color: "blue",
        birth_year: "64BBY",
        gender: "male",
        homeworld: "https://swapi.dev/api/planets/21/",
        films: ["https://swapi.dev/api/films/1/", "https://swapi.dev/api/films/6/"],
        species: [],
        vehicles: [],
        starships: [],
        created: "2014-12-10T16:26:56.138000Z",
        edited: "2014-12-20T21:17:50.330000Z",
        url: "https://swapi.dev/api/people/12/",
      },
      {
        name: "Chewbacca",
        height: "228",
        mass: "112",
        hair_color: "brown",
        skin_color: "unknown",
        eye_color: "blue",
        birth_year: "200BBY",
        gender: "male",
        homeworld: "https://swapi.dev/api/planets/14/",
        films: [
          "https://swapi.dev/api/films/1/",
          "https://swapi.dev/api/films/2/",
          "https://swapi.dev/api/films/3/",
          "https://swapi.dev/api/films/6/",
        ],
        species: ["https://swapi.dev/api/species/3/"],
        vehicles: ["https://swapi.dev/api/vehicles/19/"],
        starships: ["https://swapi.dev/api/starships/10/", "https://swapi.dev/api/starships/22/"],
        created: "2014-12-10T16:42:45.066000Z",
        edited: "2014-12-20T21:17:50.332000Z",
        url: "https://swapi.dev/api/people/13/",
      },
    ],
  ],
  next: "https://swapi.dev/api/people/?page=3",
  previous: "https://swapi.dev/api/people/?page=1",
  count: 82,
};

export const homeworldMock: Homeworld = {
  name: "Tatooine",
  rotation_period: "23",
  orbital_period: "304",
  diameter: "10465",
  climate: "arid",
  gravity: "1 standard",
  terrain: "desert",
  surface_water: "1",
  population: "200000",
  residents: [
    "https://swapi.dev/api/people/1/",
    "https://swapi.dev/api/people/2/",
    "https://swapi.dev/api/people/4/",
    "https://swapi.dev/api/people/6/",
    "https://swapi.dev/api/people/7/",
    "https://swapi.dev/api/people/8/",
    "https://swapi.dev/api/people/9/",
    "https://swapi.dev/api/people/11/",
    "https://swapi.dev/api/people/43/",
    "https://swapi.dev/api/people/62/",
  ],
  films: [
    "https://swapi.dev/api/films/1/",
    "https://swapi.dev/api/films/3/",
    "https://swapi.dev/api/films/4/",
    "https://swapi.dev/api/films/5/",
    "https://swapi.dev/api/films/6/",
  ],
  created: "2014-12-09T13:50:49.641000Z",
  edited: "2014-12-20T20:58:18.411000Z",
  url: "https://swapi.dev/api/planets/1/",
};

export const paginatedHomeworldsMock = {
  count: 82,
  next: "https://swapi.dev/api/people/?page=2",
  previous: null,
  results: [
    {
      name: "Luke Skywalker",
      height: "172",
      mass: "77",
      hair_color: "blond",
      skin_color: "fair",
      eye_color: "blue",
      birth_year: "19BBY",
      gender: "male",
      homeworld: "https://swapi.dev/api/planets/1/",
      films: [
        "https://swapi.dev/api/films/1/",
        "https://swapi.dev/api/films/2/",
        "https://swapi.dev/api/films/3/",
        "https://swapi.dev/api/films/6/",
      ],
      species: [],
      vehicles: ["https://swapi.dev/api/vehicles/14/", "https://swapi.dev/api/vehicles/30/"],
      starships: ["https://swapi.dev/api/starships/12/", "https://swapi.dev/api/starships/22/"],
      created: "2014-12-09T13:50:51.644000Z",
      edited: "2014-12-20T21:17:56.891000Z",
      url: "https://swapi.dev/api/people/1/",
    },
    {
      name: "C-3PO",
      height: "167",
      mass: "75",
      hair_color: "n/a",
      skin_color: "gold",
      eye_color: "yellow",
      birth_year: "112BBY",
      gender: "n/a",
      homeworld: "https://swapi.dev/api/planets/1/",
      films: [
        "https://swapi.dev/api/films/1/",
        "https://swapi.dev/api/films/2/",
        "https://swapi.dev/api/films/3/",
        "https://swapi.dev/api/films/4/",
        "https://swapi.dev/api/films/5/",
        "https://swapi.dev/api/films/6/",
      ],
      species: ["https://swapi.dev/api/species/2/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:10:51.357000Z",
      edited: "2014-12-20T21:17:50.309000Z",
      url: "https://swapi.dev/api/people/2/",
    },
    {
      name: "R2-D2",
      height: "96",
      mass: "32",
      hair_color: "n/a",
      skin_color: "white, blue",
      eye_color: "red",
      birth_year: "33BBY",
      gender: "n/a",
      homeworld: "https://swapi.dev/api/planets/8/",
      films: [
        "https://swapi.dev/api/films/1/",
        "https://swapi.dev/api/films/2/",
        "https://swapi.dev/api/films/3/",
        "https://swapi.dev/api/films/4/",
        "https://swapi.dev/api/films/5/",
        "https://swapi.dev/api/films/6/",
      ],
      species: ["https://swapi.dev/api/species/2/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:11:50.376000Z",
      edited: "2014-12-20T21:17:50.311000Z",
      url: "https://swapi.dev/api/people/3/",
    },
  ],
};
